on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"
          - "3.11"
    name: Check Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install nox
        run: pip install nox

      - name: install build
        run: pip install build

      - name: build this thing
        run: python -m build . --wheel

      - name: install this thing
        run: pip install .

      - name: Test package
        run: python -m nox

  format:
    runs-on: ubuntu-latest
    name: Run precommit
    steps:
      - uses: actions/checkout@v3

      - name: install pre-commit
        run: pip install pre-commit

      - name: run against all files
        run: pre-commit run --all-files
